# Generated by Django 4.2.7 on 2026-04-11 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('author_bio', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured_image_url', models.URLField(blank=True)),
                ('featured_image_alt', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'published_at'], name='blogs_blog_status_2d775f_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', 'status'], name='blogs_blog_categor_c20b81_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blogs_blog_slug_d0bba8_idx'),
        ),
    ]
