# Generated by Django 4.2.7 on 2026-04-11 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('message', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('contact_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Support'), ('partnership', 'Partnership'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('response_content', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='contacts_co_status_5f2ec4_idx'), models.Index(fields=['email'], name='contacts_co_email_25f973_idx'), models.Index(fields=['contact_type'], name='contacts_co_contact_d678b6_idx')],
            },
        ),
    ]
