# Generated by Django 4.2.7 on 2026-04-11 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, max_length=2000)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive Level')], max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('immediately', 'Immediately'), ('2-weeks', '2 Weeks'), ('1-month', '1 Month'), ('3-months', '3 Months'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'), models.Index(fields=['email'], name='application_email_c09a19_idx')],
            },
        ),
    ]
