# Generated by Django 4.2.7 on 2026-04-11 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('company', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('location', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full-time', max_length=20)),
                ('category', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='EUR', max_length=3)),
                ('salary_period', models.CharField(choices=[('hour', 'per hour'), ('day', 'per day'), ('week', 'per week'), ('month', 'per month'), ('year', 'per year')], default='year', max_length=10)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
                'indexes': [models.Index(fields=['category', 'location', 'job_type'], name='jobs_job_categor_ba012e_idx'), models.Index(fields=['is_active', 'featured'], name='jobs_job_is_acti_d606c0_idx')],
            },
        ),
    ]
